apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  selector:
    app: customer
  ports:
    - port: 80 # дефолтный порт нашей worker node
      targetPort: 8080
  type: LoadBalancer # kubernetes service будет типа балансировщик нагрузки